### ISSUE TITLE
Patches pool is non-existent error.

### ISSUE THREAD

**Issue by rajdeep-biswas** [ali-ghanbari/prf#8]
I used [this sample maven app](https://github.com/jenkins-docs/simple-java-maven-app) to run the patcher on; I cloned the repo and ran the `mvn clean test` command which executed successfully.

On running `mvn edu.utdallas:prf-maven-plugin:run -Dhttps.protocols=TLSv1.2`, the following error is received -

```java
[INFO] --- prf-maven-plugin:1.0-SNAPSHOT:run (default-cli) @ my-app ---
[INFO] Found Patch Generation Plugin: dummy-patch-generation-plugin (Dummy patch generation plugin)
[INFO] Found Patch Prioritization Plugin: dummy-patch-prioritization-plugin (Dummy patch prioritization plugin)
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=16g; support was removed in 8.0
Installing PIT agent
Profiler is HERE!
Profiler is DONE!
INFO: Dummy patch generation plugin initialized.
org.apache.maven.plugin.MojoFailureException: Patches pool is non-existent
        at edu.utdallas.prf.PRFEntryPoint.runPatchGenerator(PRFEntryPoint.java:335)
        at edu.utdallas.prf.PRFEntryPoint.run(PRFEntryPoint.java:249)
        at edu.utdallas.prf.maven.AbstractPRFMojo.execute(AbstractPRFMojo.java:233)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.941 s
[INFO] Finished at: 2021-10-19T12:06:18+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal edu.utdallas:prf-maven-plugin:1.0-SNAPSHOT:run (default-cli) on project my-app: Patches pool is non-existent -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException```

**Comment by ali-ghanbari** [comment]
Hi,

I'm sorry for belated response.
It looks like PRF has invoked _dummy patch generator_ and that is looking for possible patches under the directory `patches-pool` which does not exist.
You might want to configure the POM file, so that CapGen, or any other patch generation system that you have, run and generate those patches for you.
